name: ShellScriptTest
on: [push]
jobs:
  gcd_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo test greatest-common-divisor
          echo GitHubAction CI test in ci.yml
          ./greatest_common_divisor_test.sh
